'use client'

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import React from 'react'
import LayoutComponent from '../components/Layout'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (<>
        <html lang="en">
            <head>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="theme-color" content="#000000" />
                <meta name="description" content="Web site created using create-react-app" />

                <title>React App</title>
                <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />

                <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
                <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />

                {/* <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia&display=optional" /> */}
                <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
            </head>

            <body>
                <noscript>You need to enable JavaScript to run this app.</noscript>
                <div id="root">
                    <React.StrictMode>
                        <LayoutComponent>
                            {children}
                        </LayoutComponent>
                    </React.StrictMode>
                </div>
            </body>
        </html>
    </>)
}
